### ISSUE TITLE
Questions for infrastructure admin.

### ISSUE THREAD

**Issue by scollier** [whitel/summit-2015-lab-15812#13]
1. will we have a list of workstation MAC and IP so we can execute commands on all of them?
2. will we have root / sudo privileges?
3. can he host a content VM with packages?
4. if we want to plug 2 laptops into the network and obtain student subnet IP addresses and serve content, can we?
5. how will lab material (guide) be distibuted to students?

**Comment by whitel** [comment]
Sent queries to Scott McBrien
