### ISSUE TITLE
get multiple copies of content VM

### ISSUE THREAD

**Issue by scollier** [whitel/summit-2015-lab-15812#18]
someone from Westford needs to grab a copy, and I will too.

**Comment by scollier** [comment]
@aweiteka i'll grab one, and maybe you can grab one?  just for backup.

**Comment by whitel** [comment]
if one of y'all can tell me where to get it, I can also get a copy.

**Comment by scollier** [comment]
@whitel I'll send locations for wget once we finalize.  going to leave this open so i don't forget.

**Comment by scollier** [comment]
closing because we are sending copy to Scott M.  I don't have to set this up.
