### ISSUE TITLE
fix up transitions

### ISSUE THREAD

**Issue by whitel** [whitel/summit-2015-lab-15812#33]
when we leave lab1, we are root in /root/lab1, when we start lab2 the first command is "cd bigapp" .. it should be something more like "exit; cd ~/; cd sync/lab2; cd bigapp"

arguably, and this is why this is an issue, we should all do "root" or all do "regular user"

**Comment by whitel** [comment]
also, should the end of each lab be a "shutdown" phase?

**Comment by scollier** [comment]
sure, a shutdown phase would be OK.  also, a absolute path would work too.

cd /home/user1/bigapp    or w/e it is.  then it doesn't matter where you are.

**Comment by dustymabe** [comment]
yeah I didn't know where to start for lab 2. is there somewhere that there exists a diagram of what the file layout will be on these machines?

**Comment by whitel** [comment]
@dustymabe it will be /home/vagrant/sync/ then whatever is here: https://github.com/whitel/summit-2015-lab-15812/tree/master/vagrant

**Comment by dustymabe** [comment]
I'm confused.. I didn't think vagrant or any mention of vagrant would be in our actual lab environment. It would be odd to tell them to cd to /home/vagrant/sync/ when we aren't using vagrant.

**Comment by whitel** [comment]
well.. the images we will be using are the one's vagrant creates, so.. the user is "vagrant" and home-dir is /home/vagrant ... I suppose we can change the user, i just wasn't planning on bothering :)

**Comment by dustymabe** [comment]
from irc discussion with scott and aaron:

paths should be: /root/lab{1,2,3,4,5}/  which map to our current: /home/vagrant/sync/vagrant/lab{1,2,3,4,5}
