### ISSUE TITLE
lab 4 notes

### ISSUE THREAD

**Issue by scollier** [whitel/summit-2015-lab-15812#51]
at the beginning, we don't need to rm the containers because we did that at the end of lab 3.

I was not able to open a browser to my vagrant VM.
"curl -L http://localhost"       on that host works.  see:

```
#   curl -L http://localhost
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Database Error</title>

</head>
<body>
	<h1>Error establishing a database connection</h1>
</body>
</html>
```

after the second "docker start mariadb", the web site did not come back up.  still error establishing connection.

both containers were up:

```
# docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS                    NAMES
b5fbf835b3a9        wordpress:latest    "/bin/bash /scripts/   5 minutes ago       Up 5 minutes        0.0.0.0:80->80/tcp       wordpress           
35b9945fe56b        mariadb:latest      "/bin/bash /scripts/   5 minutes ago       Up About a minute   0.0.0.0:3306->3306/tcp   mariadb             
```

this was a  tad confusing:

Replace the 
containers:

  containers:
  - capabilities: {}
    env:
    image: YOUR_LAB_DEV_MACHINE:5000/mariadb
    name: mariadb
    ports:
    - containerPort: 3306
      protocol: TCP
    resources:
      limits:
        cpu: 100m

after we do the creates, should we curl to make sure they work?

same thing after launching services.  we need to confirm functionality.

before this sentence:

"All right, let's switch to the remote, don't forget to replace YOUR_LAB_DEPLOY_MACHINE with the correct name:"

we need to tell them how to get that IP, or what it is, etc...

i got lost here, but it's 12:20am.  fried.  we'll discuss tomorrow.

```
ssh root@summit_rhel_deploy_target
ssh -L *:9080:<WPFRONTEND_ENDPOINT>:80 root@localhost
```

I finished everything else, was really cool with kubectl.  I hadn't done the context stuff before.

**Comment by whitel** [comment]
We actually do verify the stuff is up. We can't test the "website" because we only have pods and they connect across services (not pod to pod direct). It *may* work because our containers happen to tolerate getting the env info from a bunch of ways but it isn't "supposed" too.
