### ISSUE TITLE
Fixup transition between lab 4/5

### ISSUE THREAD

**Issue by dustymabe** [whitel/summit-2015-lab-15812#63]
We need to delete the kube services between lab4/lab5 otherwise we end up with:

Error: service "mariadb" already exists

**Comment by dustymabe** [comment]
Also you may want to make it clear that we are executing things in the "remote-context" so that what happens actually gets runs on the deploy (atomic) server. may want to add a step in there to have them *verify* they are in the using the remote context

**Comment by aweiteka** [comment]
Resolved by https://github.com/whitel/summit-2015-lab-15812/commit/ef9f01a646e774521e25470b0df9c17f62f1fc2f
