### ISSUE TITLE
chapter 4 needs to be modified

### ISSUE THREAD

**Issue by scollier** [whitel/summit-2015-lab-15812#71]
192.168.135.2:5000/mariadb": API error (500):  v1 ping attempt failed with error: Get https://192.168.135.2:5000/v1/_ping: dial tcp 192.168.135.2:5000: connection refused. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry 192.168.135.2:5000` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/192.168.135.2:5000/ca.crt

**Comment by whitel** [comment]
fixed to use dns names. I think the issue was the hard coded ip.
