### ISSUE TITLE
hostnames within qcow images reflect vagrant environment

### ISSUE THREAD

**Issue by dustymabe** [whitel/summit-2015-lab-15812#76]
The images that I downloaded still have the hostnames reflecting the vagrant environment and not the new lab environment that we will be using at summit.

on dev:
[root@summit-rhel-dev ~]# hostname
summit-rhel-dev

on deploy:
-bash-4.2# hostname
summit-rhel-deploy-target

**Comment by whitel** [comment]
i think this is all fixed in latest (building now)
