### ISSUE TITLE
Remove all hacks around dns for content server

### ISSUE THREAD

**Issue by dustymabe** [whitel/summit-2015-lab-15812#77]
Going forward we are using the libvirt/qcow2 environment for all testing. Since this environment has the content server properly defined in the network xml file so that dns resolution works let's remove all nasty hacks that we have used to work around this. Some examples are:

```
RUN cat /new-hosts >> /etc/hosts && yum -y update && yum clean all
```

```
docker run -dt -p 80:80 --net=host --name apache redhat/apache
```

Also are we using `content.example.com` now instead of `content.server.lcl` ?

**Comment by dustymabe** [comment]
As part of this migration we also need to make sure we rip the entry out of /etc/hosts inside the images.

**Comment by whitel** [comment]
I think this is complete.
