### ISSUE TITLE
Include Dockerfile_linter

### ISSUE THREAD

**Issue by aweiteka** [whitel/summit-2015-lab-15812#9]
I've got dockerfile_linter working as CLI. We can build this into the VM.

**Comment by whitel** [comment]
If you tell me where it is on docker hub, I can add this to the Vagrantfile

**Comment by aweiteka** [comment]
https://github.com/projectatomic/dockerfile_lint#command-line-use

Assuming we have the epel repo content...

1. `yum install -y npm`
1. `npm install git+https://github.com/projectatomic/dockerfile_lint`
1. `dockerfile_lint  -f /path/to/dockerfile`

**Comment by scollier** [comment]
removing from lab.
